// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF-oLVJTLkD0RBugXT_M8jeqtMJDlMDAU',
    appId: '1:341374016835:web:d325f5de44be9407af23f6',
    messagingSenderId: '341374016835',
    projectId: 'issue-tracker-2d84e',
    authDomain: 'issue-tracker-2d84e.firebaseapp.com',
    storageBucket: 'issue-tracker-2d84e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvplCq_0pqVKIr4QpKJ2ExKHYmsNaLB9g',
    appId: '1:341374016835:android:9116c0ef96113a26af23f6',
    messagingSenderId: '341374016835',
    projectId: 'issue-tracker-2d84e',
    storageBucket: 'issue-tracker-2d84e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC96gemObTeH8LYupNI1vxNFsyD2-PaceQ',
    appId: '1:341374016835:ios:6c7d9a0220406f58af23f6',
    messagingSenderId: '341374016835',
    projectId: 'issue-tracker-2d84e',
    storageBucket: 'issue-tracker-2d84e.appspot.com',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC96gemObTeH8LYupNI1vxNFsyD2-PaceQ',
    appId: '1:341374016835:ios:4c73a4b18fb94e86af23f6',
    messagingSenderId: '341374016835',
    projectId: 'issue-tracker-2d84e',
    storageBucket: 'issue-tracker-2d84e.appspot.com',
    iosBundleId: 'com.example.timeTracker.RunnerTests',
  );
}
